// Mocks generated by Mockito 5.4.1 from annotations
// in heb/test/presentation/bloc/pokemon_bloc_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:heb/app/domain/entities/pokemon_detail_response.entity.dart'
    as _i9;
import 'package:heb/app/domain/entities/pokemon_response.entity.dart' as _i7;
import 'package:heb/app/domain/repositories/pokemon.repository.dart' as _i2;
import 'package:heb/app/domain/usecases/get_pokemon_detail.usecase.dart' as _i8;
import 'package:heb/app/domain/usecases/get_pokemon_list.usecase.dart' as _i4;
import 'package:heb/core/exceptions/custom.exceptions.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonRepository_0 extends _i1.SmartFake
    implements _i2.PokemonRepository {
  _FakePokemonRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetPokemonListUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonListUsecase extends _i1.Mock
    implements _i4.GetPokemonListUsecase {
  MockGetPokemonListUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get pokemonRepository => (super.noSuchMethod(
        Invocation.getter(#pokemonRepository),
        returnValue: _FakePokemonRepository_0(
          this,
          Invocation.getter(#pokemonRepository),
        ),
      ) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.Either<_i6.CustomException, _i7.PokemonResponse>> execute(
          {required String? next}) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {#next: next},
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.CustomException, _i7.PokemonResponse>>.value(
            _FakeEither_1<_i6.CustomException, _i7.PokemonResponse>(
          this,
          Invocation.method(
            #execute,
            [],
            {#next: next},
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.CustomException, _i7.PokemonResponse>>);
}

/// A class which mocks [GetPokemonDetailUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonDetailUsecase extends _i1.Mock
    implements _i8.GetPokemonDetailUsecase {
  MockGetPokemonDetailUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get pokemonRepository => (super.noSuchMethod(
        Invocation.getter(#pokemonRepository),
        returnValue: _FakePokemonRepository_0(
          this,
          Invocation.getter(#pokemonRepository),
        ),
      ) as _i2.PokemonRepository);
  @override
  _i5.Future<_i3.Either<_i6.CustomException, _i9.PokemonDetailResponse>>
      execute({required String? url}) => (super.noSuchMethod(
            Invocation.method(
              #execute,
              [],
              {#url: url},
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.CustomException,
                        _i9.PokemonDetailResponse>>.value(
                _FakeEither_1<_i6.CustomException, _i9.PokemonDetailResponse>(
              this,
              Invocation.method(
                #execute,
                [],
                {#url: url},
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.CustomException, _i9.PokemonDetailResponse>>);
}
