// Mocks generated by Mockito 5.4.1 from annotations
// in heb/test/test_hepers/test_hepers.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i5;
import 'package:heb/app/data/datasources/remote/interfaces/pokemon.remote.source.dart'
    as _i11;
import 'package:heb/app/data/models/pokemon_detail_response.model.dart' as _i4;
import 'package:heb/app/data/models/pokemon_response.model.dart' as _i3;
import 'package:heb/app/domain/entities/pokemon_detail_response.entity.dart'
    as _i10;
import 'package:heb/app/domain/entities/pokemon_response.entity.dart' as _i9;
import 'package:heb/app/domain/repositories/pokemon.repository.dart' as _i6;
import 'package:heb/core/exceptions/custom.exceptions.dart' as _i8;
import 'package:heb/core/services/network/http.service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonResponseModel_1 extends _i1.SmartFake
    implements _i3.PokemonResponseModel {
  _FakePokemonResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonDetailResponseModel_2 extends _i1.SmartFake
    implements _i4.PokemonDetailResponseModel {
  _FakePokemonDetailResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i5.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i6.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.CustomException, _i9.PokemonResponse>> getPokemons(
          {required String? next}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {#next: next},
        ),
        returnValue: _i7.Future<
                _i2.Either<_i8.CustomException, _i9.PokemonResponse>>.value(
            _FakeEither_0<_i8.CustomException, _i9.PokemonResponse>(
          this,
          Invocation.method(
            #getPokemons,
            [],
            {#next: next},
          ),
        )),
      ) as _i7.Future<_i2.Either<_i8.CustomException, _i9.PokemonResponse>>);
  @override
  _i7.Future<_i2.Either<_i8.CustomException, _i10.PokemonDetailResponse>>
      getPokemonDetail({required String? url}) => (super.noSuchMethod(
            Invocation.method(
              #getPokemonDetail,
              [],
              {#url: url},
            ),
            returnValue: _i7.Future<
                    _i2.Either<_i8.CustomException,
                        _i10.PokemonDetailResponse>>.value(
                _FakeEither_0<_i8.CustomException, _i10.PokemonDetailResponse>(
              this,
              Invocation.method(
                #getPokemonDetail,
                [],
                {#url: url},
              ),
            )),
          ) as _i7.Future<
              _i2.Either<_i8.CustomException, _i10.PokemonDetailResponse>>);
}

/// A class which mocks [PokemonRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteSource extends _i1.Mock
    implements _i11.PokemonRemoteSource {
  MockPokemonRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.PokemonResponseModel> getPokemons({required String? next}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemons,
          [],
          {#next: next},
        ),
        returnValue: _i7.Future<_i3.PokemonResponseModel>.value(
            _FakePokemonResponseModel_1(
          this,
          Invocation.method(
            #getPokemons,
            [],
            {#next: next},
          ),
        )),
      ) as _i7.Future<_i3.PokemonResponseModel>);
  @override
  _i7.Future<_i4.PokemonDetailResponseModel> getPokemonDetail(
          {required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPokemonDetail,
          [],
          {#url: url},
        ),
        returnValue: _i7.Future<_i4.PokemonDetailResponseModel>.value(
            _FakePokemonDetailResponseModel_2(
          this,
          Invocation.method(
            #getPokemonDetail,
            [],
            {#url: url},
          ),
        )),
      ) as _i7.Future<_i4.PokemonDetailResponseModel>);
}

/// A class which mocks [HttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i12.HttpService {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
      ) as String);
  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
        Invocation.setter(
          #baseUrl,
          _baseUrl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set interceptors(List<_i5.Interceptor>? _interceptors) => super.noSuchMethod(
        Invocation.setter(
          #interceptors,
          _interceptors,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i5.Response<dynamic>> get(
    String? uri, {
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [uri],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [uri],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> post(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> delete(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #delete,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> patch(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #patch,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
  @override
  _i7.Future<_i5.Response<dynamic>> put(
    String? uri, {
    Map<String, dynamic>? body,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [uri],
          {
            #body: body,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i7.Future<_i5.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #put,
            [uri],
            {
              #body: body,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i7.Future<_i5.Response<dynamic>>);
}
